version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  auth-service:
    build: ./backend/auth-service
    ports:
      - "4001:4001"
  session-service:
    build: ./backend/session-service
    ports:
      - "4002:4002"
  payment-service:
    build: ./backend/payment-service
    ports:
      - "4003:4003"